// This file is auto-generated by scripts/commands/genCommandsList.ts
// Do not edit this file manually

import type { ThemePreference } from ".";

export interface CommandsWithArgs {
  "set_theme": {
    return: undefined;
    args: {
      theme: ThemePreference;
    };
  };
  "update_timestamp": {
    return: undefined;
    args: {
      timestamp: number;
      topic: string;
    };
  };
  "get_timestamp": {
    return: number;
    args: {
      topic: string;
    };
  };
  "save_data": {
    return: undefined;
    args: {
      data: TopicData;
      topic: string;
    };
  };
  "load_data": {
    return: TopicData | null;
    args: {
      topic: string;
    };
  };
  "remove_subtopic": {
    return: undefined;
    args: {
      subtopic: string;
      topic: string;
    };
  };
};

export interface CommandsWithoutArgs {
  "get_imgbb_key": {
    return: string;
  };
  "get_theme": {
    return: ThemePreference;
  };
  "get_firebase_key": {
    return: string;
  };
};

export type Commands = CommandsWithArgs | CommandsWithoutArgs;
