// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Représente une réponse de QCU/QCM.
 */
export type Answer = { 
/**
 * La réponse.
 */
label: string, 
/**
 * Est-ce que c'est une bonne réponse ou non.
 * Est Some seulement si `true`, sinon None.
 */
isAnswer: boolean | null, };

/**
 * Représente une question de QCU/QCM.
 */
export type Question = { 
/**
 * Le texte de la question.
 */
label: string, 
/**
 * URL de l'image associée à la question s'il y en a.
 */
image: string | null, 
/**
 * Les réponses possibles.
 */
answers: Array<Answer>, 
/**
 * L'explication de pourquoi les réponses correctes le sont.
 */
explanation: string, };
