// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Représente la préférence de thème d'un utilisateur, qui peut être "light", "dark" ou "system".
 */
export type ThemePreference = "light" | "dark" | "system";
