import fs from "fs/promises";
import path from "path";
import { getCommandsInfo } from "./getCommandArgs";

interface CommandWithArgs {
  name: string;
  return: string;
  args: { [argName: string]: string | undefined };
}
interface CommandWithoutArgs {
  name: string;
  return: string;
}

// #region:    --Commands List Generation
export async function genCommandsList() {
  const outPath = path.resolve(__dirname, "../../bindings/commandsList.ts");
  const libRs = path.resolve(__dirname, "../../../src-tauri/src/lib.rs");

  // Read and parse the lib.rs file
  const data = await fs.readFile(libRs, "utf-8");
  const commands = parseLibFile(data);

  // Get the commands info
  const { imports, commands: commandsWithInfo } = await getCommandsInfo(commands);

  const commandsWithArgs: CommandWithArgs[] = [];
  const commandsWithoutArgs: CommandWithoutArgs[] = [];

  for (const commandName in commandsWithInfo) {
    const { returnType, ...args } = commandsWithInfo[commandName]!;

    if (Object.keys(args).length === 0) {
      commandsWithoutArgs.push({
        name: commandName,
        return: returnType || "void",
      });
      continue;
    }

    commandsWithArgs.push({
      name: commandName,
      return: returnType || "void",
      args,
    });
  }

  const argsInterface = commandsWithArgs.length
    ? ["export interface CommandsWithArgs {", stringify(commandsWithArgs), "};"].join("\n")
    : [
        "// eslint-disable-next-line @typescript-eslint/no-empty-object-type",
        "export interface CommandsWithArgs {};",
      ].join("\n");

  const noArgsInterface = commandsWithoutArgs.length
    ? ["export interface CommandsWithoutArgs {", stringify(commandsWithoutArgs), "};"].join("\n")
    : [
        "// eslint-disable-next-line @typescript-eslint/no-empty-object-type",
        "export interface CommandsWithoutArgs {};",
      ].join("\n");

  // Generate the file content
  const content = [
    "// This file is auto-generated by scripts/commands/genCommandsList.ts",
    `// Do not edit this file manually`,
    imports.size ? `\nimport type { ${Array.from(imports).join(", ")} } from ".";\n` : "",
    argsInterface,
    "",
    noArgsInterface,
    "",
    "export type Commands = CommandsWithArgs | CommandsWithoutArgs;",
    "",
  ].join("\n");

  // Write the content to the file
  await fs.writeFile(outPath, content, "utf-8");
  console.log(`Command list generated at ${outPath}`);
}

function parseLibFile(data: string) {
  // Regex to find the content of tauri::generate_handler![...]
  const regexHandler = /tauri::generate_handler!\[([\s\S]*?)\]/m;

  // Find the match
  const handlerMatch = data.match(regexHandler);
  if (!handlerMatch?.[1]) {
    console.log(data);

    throw new Error("No handler match found");
  }

  // Remove comments
  const uncommented = handlerMatch[1].replace(/\/\/.*$/gm, "");

  // Split the result by comma
  return uncommented.split(",").map((item) => item.trim());
}
// #endregion: --Commands List Generation

// #region:    --Utils
function stringify<T extends CommandWithArgs | CommandWithoutArgs>(commands: T[]) {
  return commands
    .map((command) => {
      const res = [`  "${command.name}": {`, `    return: ${command.return};`];

      const args =
        "args" in command &&
        Object.entries(command.args)
          .map(([argName, argType]) => `      ${argName}: ${argType};`)
          .join("\n");

      if (args) {
        res.push(`    args: {\n${args}\n    };`);
      }

      res.push("  };");

      return res.join("\n");
    })
    .join("\n");
}
// #endregion: --Utils
