import fs, { appendFile } from "fs/promises";
import path from "path";
import { $ } from "bun";

async function exportBindings(basePath: string = __dirname) {
  const files = await fs.readdir(basePath);

  const cleaned: string[] = [];

  for (const item of files) {
    if (item === "index.ts") continue;

    if (!item.endsWith(".ts")) {
      // This is a subdirectory, recurse into it
      const subdirPath = path.join(basePath, item);
      await exportBindings(subdirPath);
    }

    const fileName = item.replace(".ts", "");
    cleaned.push(`export * from './${fileName}';`);

    if (item === "auth.ts") {
      // Cas particulier, on ajoute l'export des permissions
      const permissions = await prepareUserActions();
      const exportLine = `export const PERMISSIONS = ${permissions}`;
      await appendFile(`${basePath}/${item}`, `\n${exportLine}`, "utf-8");
    }
  }

  const content = [
    `// This file is auto-generated by ~/scripts/exportBindings.ts`,
    `// Do not edit this file manually`,
    "",
    ...cleaned,
  ];

  const outPath = path.join(basePath, "index.ts");

  // Write the exports to the index.ts file
  fs.writeFile(outPath, content.join("\n"), "utf-8");

  console.log(`Exported bindings in ${outPath}`);
}

async function prepareUserActions() {
  return (await $`cd ./src-tauri && cargo run --bin generate_actions 2>/dev/null`).text();
}

(async () => {
  const bindingsPath = path.resolve(__dirname, "../bindings");

  await exportBindings(bindingsPath);
})().catch((err) => {
  console.error("Error exporting generated bindings", err);
  process.exit(1);
});
